// src/components/Button.vue
<script setup lang="ts">
import { computed } from 'vue';

// Props do componente
interface ButtonProps {
  variant?: 'primary' | 'secondary' | 'tertiary' | 'danger' | 'success' | 'warning' | 'info';
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  rounded?: 'none' | 'sm' | 'md' | 'lg' | 'xl' | 'full';
  href?: string;
  disabled?: boolean;
  fullWidth?: boolean;
  type?: 'button' | 'submit' | 'reset';
  customClass?: string;
  external?: boolean;
}

const props = withDefaults(defineProps<ButtonProps>(), {
  variant: 'primary',
  size: 'md',
  rounded: 'md',
  disabled: false,
  fullWidth: false,
  type: 'button',
  customClass: '',
  external: false
});

// Emits para eventos
const emit = defineEmits(['click']);

// Estilos base para todos os botões
const baseStyles = 'inline-flex items-center justify-center font-medium transition-all duration-300 focus:outline-none focus:ring-2 focus:ring-offset-2 shadow-lg hover:shadow-xl transform hover:-translate-y-0.5';

// Estilos específicos para cada variante
const variantStyles = computed(() => {
  switch (props.variant) {
    case 'primary':
      return 'bg-gradient-to-r from-emerald-500 to-green-600 text-white hover:from-emerald-600 hover:to-green-700 focus:ring-emerald-500';
    case 'secondary':
      return 'bg-white border-2 border-emerald-500 text-emerald-600 hover:bg-emerald-50 hover:border-emerald-600 focus:ring-emerald-500';
    case 'tertiary':
      return 'bg-transparent text-emerald-600 hover:bg-emerald-50 focus:ring-emerald-500';
    case 'danger':
      return 'bg-gradient-to-r from-red-500 to-red-600 text-white hover:from-red-600 hover:to-red-700 focus:ring-red-500';
    case 'success':
      return 'bg-gradient-to-r from-green-500 to-emerald-600 text-white hover:from-green-600 hover:to-emerald-700 focus:ring-green-500';
    case 'warning':
      return 'bg-gradient-to-r from-yellow-400 to-amber-500 text-white hover:from-yellow-500 hover:to-amber-600 focus:ring-yellow-500';
    case 'info':
      return 'bg-gradient-to-r from-blue-500 to-blue-600 text-white hover:from-blue-600 hover:to-blue-700 focus:ring-blue-500';
    default:
      return 'bg-gradient-to-r from-emerald-500 to-green-600 text-white hover:from-emerald-600 hover:to-green-700 focus:ring-emerald-500';
  }
});

// Estilos para diferentes tamanhos
const sizeStyles = computed(() => {
  switch (props.size) {
    case 'xs':
      return 'text-xs px-3 py-1.5';
    case 'sm':
      return 'text-sm px-4 py-2';
    case 'md':
      return 'text-base px-6 py-3';
    case 'lg':
      return 'text-lg px-8 py-4';
    case 'xl':
      return 'text-xl px-10 py-5';
    default:
      return 'text-base px-6 py-3';
  }
});

// Estilos para diferentes arredondamentos
const roundedStyles = computed(() => {
  switch (props.rounded) {
    case 'none':
      return 'rounded-none';
    case 'sm':
      return 'rounded-sm';
    case 'md':
      return 'rounded-xl';
    case 'lg':
      return 'rounded-2xl';
    case 'xl':
      return 'rounded-3xl';
    case 'full':
      return 'rounded-full';
    default:
      return 'rounded-xl';
  }
});

// Estilos para largura total
const widthStyles = computed(() => {
  return props.fullWidth ? 'w-full' : '';
});

// Estilos para estado desabilitado
const disabledStyles = computed(() => {
  return props.disabled ? 'opacity-50 cursor-not-allowed transform-none hover:shadow-lg' : '';
});

// Classe final combinada
const buttonClass = computed(() => {
  return [
    baseStyles,
    variantStyles.value,
    sizeStyles.value,
    roundedStyles.value,
    widthStyles.value,
    disabledStyles.value,
    props.customClass
  ].join(' ');
});

// Função para lidar com cliques
const handleClick = (event: Event) => {
  if (!props.disabled) {
    emit('click', event);
  }
};
</script>

<template>
  <!-- Link externo -->
  <a 
    v-if="href && external" 
    :href="href" 
    target="_blank" 
    rel="noopener noreferrer"
    :class="buttonClass"
  >
    <slot />
  </a>
  
  <!-- Link interno -->
  <router-link 
    v-else-if="href" 
    :to="href" 
    :class="buttonClass"
  >
    <slot />
  </router-link>
  
  <!-- Botão normal -->
  <button 
    v-else
    :type="type"
    :disabled="disabled"
    :class="buttonClass"
    @click="handleClick"
  >
    <slot />
  </button>
</template>

// src/components/Button.svelte
<script lang="ts">
	// import { twMerge } from 'tailwind-merge';
	import { createEventDispatcher } from 'svelte';

	export let variant: 'primary' | 'accent' | 'outline' | 'light' | 'gray' | 'ghost' = 'primary';
	export let size: 'sm' | 'md' | 'lg' = 'md';
	export let rounded: 'sm' | 'md' | 'lg' | 'full' = 'lg';
	export let href: string | undefined = undefined;
	export let disabled: boolean = false;
	export let fullWidth: boolean = false;
	export let type: 'button' | 'submit' | 'reset' = 'button';
	export let customClass: string = '';

	// Base classes for all buttons
	const baseStyles =
		'inline-flex items-center justify-center font-semibold transition-all duration-300 focus:outline-none focus:ring-2 focus:ring-offset-2';

	// Variant specific styles
	const variantStyles = {
		primary: {
			classes:
				'bg-gradient-to-r from-emerald-600 to-emerald-700 text-white focus:ring-emerald-500 shadow-lg',
			hover: 'hover:from-emerald-700 hover:to-emerald-800 hover:shadow-xl hover:-translate-y-1'
		},
		accent: {
			classes:
				'bg-gradient-to-r from-emerald-500 to-yellow-400 text-white focus:ring-emerald-400 shadow-lg',
			hover: 'hover:shadow-xl hover:-translate-y-1' // Original examples don't show gradient change on hover for this
		},
		outline: {
			classes: 'border-2 border-emerald-600 text-emerald-600 bg-transparent focus:ring-emerald-500',
			hover: 'hover:bg-emerald-600 hover:text-white' // Matches "Ver Demonstração" button
		},
		light: {
			classes: 'bg-white text-emerald-600 focus:ring-emerald-500 shadow-lg',
			hover: 'hover:bg-gray-100 hover:shadow-xl hover:-translate-y-1'
		},
		gray: {
			classes: 'bg-gray-100 text-gray-800 focus:ring-gray-500 shadow-md', // Matches "Testar grátis" on Inicial plan
			hover: 'hover:bg-gray-200 hover:shadow-lg'
		},
		ghost: {
			classes: 'text-gray-600 hover:text-emerald-600 focus:ring-emerald-500',
			hover: 'hover:bg-emerald-50'
		}
	};

	// Size specific styles
	const sizeStyles = {
		sm: 'px-4 py-2 text-sm',
		md: 'px-6 py-2 text-base', // Based on header button
		lg: 'px-8 py-4 text-lg' // Based on hero buttons
	};

	// Rounded corner styles
	const roundedStyles = {
		sm: 'rounded-sm',
		md: 'rounded-md',
		lg: 'rounded-lg',
		full: 'rounded-full'
	};

	let klasses: string;
	$: {
		const currentVariant = variantStyles[variant];
		klasses = [
			baseStyles,
			currentVariant.classes,
			sizeStyles[size],
			roundedStyles[rounded],
			fullWidth ? 'w-full' : '',
			disabled ? 'opacity-50 cursor-not-allowed' : currentVariant.hover,
			customClass
		]
			.filter(Boolean)
			.join(' ');
	}

	const dispatch = createEventDispatcher();

	function handleClick(event: MouseEvent) {
		if (disabled) {
			event.preventDefault();
			return;
		}
		dispatch('click', event);
	}
</script>

{#if href}
	<a
		{...$$restProps}
		href={disabled ? undefined : href}
		class={klasses}
		role="button"
		aria-disabled={disabled ? 'true' : undefined}
		on:click={handleClick}
		target={$$restProps.target || (href && (href.startsWith('http') || href.startsWith('//')) ? '_blank' : undefined)}
		rel={$$restProps.rel ||
			(href && (href.startsWith('http') || href.startsWith('//')) ? 'noopener noreferrer' : undefined)}
	>
		<slot>Button</slot>
	</a>
{:else}
	<button
		{...$$restProps}
		type={type}
		{disabled}
		class={klasses}
		on:click={handleClick}
	>
		<slot>Button</slot>
	</button>
{/if}
